### ISSUE TITLE
KACE-1-0-G-tasmax.yaml fails clean-cmip6 with AttributeError: 'numpy.float64' object has no attribute 'year' from standardizing step

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#439] opened 2021-12-11 00:03 UTC
New bug raised after resolving #436 via https://github.com/ClimateImpactLab/dodola/pull/151.

tasmax from KACE-1-0-G fails all (SSP, historical) standardizing/cleaning steps with the current `dodola:dev` after https://github.com/ClimateImpactLab/dodola/pull/151.

*Note* this is _not_ the `dodola` release used by the current stable clean-cmip6 workflowTemplate.

We're seeing this in workflow run https://argo.cildc6.org/archived-workflows/default/81cfd5d4-c40b-4e14-9e3d-82aac59d5e92.
Example log with error:

```
INFO:dodola.services:Starting dodola service clean_cmip6 with args=('gs://scratch-170cd6ec/81cfd5d4-c40b-4e14-9e3d-82aac59d5e
92/clean-cmip6-devknxb2-314469557/timesliced.zarr', 'gs://scratch-170cd6ec/81cfd5d4-c40b-4e14-9e3d-82aac59d5e92/clean-cmip6-d
evknxb2-3308842977/standardized.zarr', True), kwargs={})
INFO:dodola.repository:Read gs://scratch-170cd6ec/81cfd5d4-c40b-4e14-9e3d-82aac59d5e92/clean-cmip6-devknxb2-314469557/timesli
ced.zarr
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 460, in encode_cf_datetime
    raise OutOfBoundsDatetime
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 477, in cleancmip6
    services.clean_cmip6(x, out, drop_leapdays)
  File "/opt/dodola/dodola/services.py", line 35, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 730, in clean_cmip6
    storage.write(out, cleaned_ds)
  File "/opt/dodola/dodola/repository.py", line 71, in write
    x.to_zarr(url_or_path, mode="w", compute=True)
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1414, in to_zarr
    dump_to_store(dataset, zstore, writer, encoding=encoding)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1124, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/zarr.py", line 521, in store
    variables_encoded, attributes = self.encode(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/common.py", line 201, in encode
    variables = {k: self.encode_variable(v) for k, v in variables.items()}
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/common.py", line 201, in <dictcomp>
    variables = {k: self.encode_variable(v) for k, v in variables.items()}
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/zarr.py", line 480, in encode_variable
    variable = encode_zarr_variable(variable)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/zarr.py", line 276, in encode_zarr_variable
    var = conventions.encode_cf_variable(var, name=name)
  File "/opt/conda/lib/python3.9/site-packages/xarray/conventions.py", line 269, in encode_cf_variable
    var = coder.encode(var, name=name)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 513, in encode
    (data, units, calendar) = encode_cf_datetime(
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 487, in encode_cf_datetime
    num = _encode_datetime_with_cftime(dates, units, calendar)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 426, in _encode_datetime_with_cftime
    return np.array([encode_datetime(d) for d in dates.ravel()]).reshape(dates.shape)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 426, in <listcomp>
    return np.array([encode_datetime(d) for d in dates.ravel()]).reshape(dates.shape)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py", line 424, in encode_datetime
    return np.nan if d is None else cftime.date2num(d, units, calendar)
  File "src/cftime/_cftime.pyx", line 257, in cftime._cftime.date2num
  File "src/cftime/_cftime.pyx", line 351, in cftime._cftime.to_calendar_specific_datetime
AttributeError: 'numpy.float64' object has no attribute 'year'
```

**Comment by brews** [comment] 2021-12-11 00:07
Okay, so my first question is whether this is an issue with `dodola@main` or an issue with the input data...?

**Comment by emileten** [comment] 2021-12-11 00:47
hmm @brews, I know we now decided to post-pone that, but it totally looks like another bug my PR caused, on top of #436.

`standardize_gcm` runs fine and the the problem happens at storage, `cftime` seems to not be getting what it wants. And that could be very likely because of the conversion. 

If so, again if I had written a functionality for this in services we'd have avoided that, because I would have tested the interaction with `repository`.

**Comment by dgergel** [comment] 2022-02-02 01:48
@brews and @emileten, it looks like we may have already fixed this and just not followed up. Can we retest with all of the fixes that we have made in the past two months?

**Comment by brews** [comment] 2022-02-02 01:58
Yeah, I'll rerun this one. Thanks for following up, @dgergel.

**Comment by dgergel** [comment] 2022-02-02 01:59
thanks @brews!

**Comment by brews** [comment] 2022-02-02 02:30
I can confirm this run still throws this error. We also get the same error if we use the newer `dodola:0.16.1` container for the failing cleaning/standardizing step.

@emileten I'm not sure I follow what you're suggesting in [the above comment](https://github.com/ClimateImpactLab/downscaleCMIP6/issues/439#issuecomment-991394889). Sounds like you have an idea of what's going on. Another side effect from the 360 calendar conversion?

**Comment by emileten** [comment] 2022-02-02 02:52
@brews yep, I didn't have a precise idea. I will look at this tomorrow.

**Comment by emileten** [comment] 2022-02-04 06:06
Ok I found what's going on. It's a calendar conversion induced bug, either an underlying `xclim` bug (that's I think the most likely) or a wrong usage in our side. 

- Here is the latest test workflow I ran to try this : https://argo.cildc6.org/archived-workflows/default/ce6408f2-227a-4dda-bd3e-53d8fb32e450. It fails like the previous. 
- I picked the `in-zarr` from the step that fails, and managed to reproduce the bug on a jupyter environment. 
- The input dataset has a `time_bnds` dimension that specifies the bounds of a given value in the `time` dimension (so for example, February the 4th 12:00:00 is between February the 4th 00:00:00 and February the 5th 00:00:00). 
- We use `xclim`'s functions to convert the 360-days calendar to a no-leap calendar. `xclim` runs without problems, and the code fails at writing the output to the zarr store. 
- Inspecting the output data, `xclim` correctly inserts new values in `time`, but inserts `nan` in the `time_bnds` dimension. Downstream, `xarray` failed at writing a zarr file because it can't encode these `nan` values as dates. 

Sounds like an `xclim` bug to me, but I am not yet sure. I will have time to work on it my Monday (if any one wants to have a look, feel free though !).

**Comment by brews** [comment] 2022-02-04 06:22
Interesting! Nice progress

xclim had a few releases recently so might be worth checking their changelog, against the last time the QPLAD xclim fork was updated.

If we can confirm it's something broken or fixable on our end (and not bad input data format) then let's open an issue in dodola?

**Comment by emileten** [comment] 2022-02-07 05:59
Thinking about this again, I wouldn't characterize this as being a bug, but something we didn't account for.  

We're telling `xclim.core.calendar.convert_calendar` where to look for the calendar representation in our dataset : in the `time` dimension. So it inserts value there, and doesn't account for the fact that we should also insert the bounds for these new values in the `time_bnds` coordinates.

I doubt there is an option to account for this, but I'd need to check with xclim developers directly. 

Alternatively, we might be able to solve this faster by just replacing the `time_bnds` coordinates ex-post, after running the above xclim function, in our own code.

**Comment by emileten** [comment] 2022-02-14 04:43
In fact, we had decided to drop this `time_bnds` information, but that isn't effective because there is a reference mistake in the standardize gcm function.

Submitted a fix here https://github.com/ClimateImpactLab/dodola/pull/178. Verified it works here https://argo.cildc6.org/archived-workflows/default/6da813ba-47ba-45a0-95d8-36444e2bcf7b. 

Once we merge it we can try to run an e2e KACE-1-0-G tasmax workflow and if it runs through the end, we can close this.

**Comment by brews** [comment] 2022-02-14 22:33
This sounds like we're going to need a new `dodola` release for this update...

**Comment by emileten** [comment] 2022-02-15 00:13
Every thing cleans up properly in here : https://argo.cildc6.org/workflows/default/clean-cmip6-dev-775mb?tab=workflow. I am closing this.

We have not yet made a release, we're going to have a test e2e run on `dev`.

**Comment by brews** [comment] 2022-02-15 00:30
Reopening this. We've got a fix in https://github.com/ClimateImpactLab/dodola/pull/178, but that has not yet been released and used by the downscaling workflows.

**Closed** 2022-02-15 05:17 UTC
Labels: bug, tasmax bias correction and downscaling run

**Comment by emileten** [comment] 2022-02-15 14:34
@brews, it's released, and the workflow doesn't have _this_ bug anymore !
